//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeisnerWebApplication.LeisnerRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Day", Namespace="http://schemas.datacontract.org/2004/07/BWS_ASP")]
    [System.SerializableAttribute()]
    public partial class Day : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccidentsNumberk__BackingFieldField;
        
        private int Averagek__BackingFieldField;
        
        private System.DateTime Datek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AccidentsNumber>k__BackingField", IsRequired=true)]
        public int AccidentsNumberk__BackingField {
            get {
                return this.AccidentsNumberk__BackingFieldField;
            }
            set {
                if ((this.AccidentsNumberk__BackingFieldField.Equals(value) != true)) {
                    this.AccidentsNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("AccidentsNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Average>k__BackingField", IsRequired=true)]
        public int Averagek__BackingField {
            get {
                return this.Averagek__BackingFieldField;
            }
            set {
                if ((this.Averagek__BackingFieldField.Equals(value) != true)) {
                    this.Averagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Averagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Date>k__BackingField", IsRequired=true)]
        public System.DateTime Datek__BackingField {
            get {
                return this.Datek__BackingFieldField;
            }
            set {
                if ((this.Datek__BackingFieldField.Equals(value) != true)) {
                    this.Datek__BackingFieldField = value;
                    this.RaisePropertyChanged("Datek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccidentDTO", Namespace="http://schemas.datacontract.org/2004/07/BWS_ASP")]
    [System.SerializableAttribute()]
    public partial class AccidentDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccidentIDk__BackingFieldField;
        
        private int Amountk__BackingFieldField;
        
        private System.DateTime Datek__BackingFieldField;
        
        private int DeviceIDk__BackingFieldField;
        
        private int STk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AccidentID>k__BackingField", IsRequired=true)]
        public int AccidentIDk__BackingField {
            get {
                return this.AccidentIDk__BackingFieldField;
            }
            set {
                if ((this.AccidentIDk__BackingFieldField.Equals(value) != true)) {
                    this.AccidentIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("AccidentIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Amount>k__BackingField", IsRequired=true)]
        public int Amountk__BackingField {
            get {
                return this.Amountk__BackingFieldField;
            }
            set {
                if ((this.Amountk__BackingFieldField.Equals(value) != true)) {
                    this.Amountk__BackingFieldField = value;
                    this.RaisePropertyChanged("Amountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Date>k__BackingField", IsRequired=true)]
        public System.DateTime Datek__BackingField {
            get {
                return this.Datek__BackingFieldField;
            }
            set {
                if ((this.Datek__BackingFieldField.Equals(value) != true)) {
                    this.Datek__BackingFieldField = value;
                    this.RaisePropertyChanged("Datek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceID>k__BackingField", IsRequired=true)]
        public int DeviceIDk__BackingField {
            get {
                return this.DeviceIDk__BackingFieldField;
            }
            set {
                if ((this.DeviceIDk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ST>k__BackingField", IsRequired=true)]
        public int STk__BackingField {
            get {
                return this.STk__BackingFieldField;
            }
            set {
                if ((this.STk__BackingFieldField.Equals(value) != true)) {
                    this.STk__BackingFieldField = value;
                    this.RaisePropertyChanged("STk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accident", Namespace="http://schemas.datacontract.org/2004/07/BWS_ASP")]
    [System.SerializableAttribute()]
    public partial class Accident : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccidentIDk__BackingFieldField;
        
        private int Amountk__BackingFieldField;
        
        private int Drinksk__BackingFieldField;
        
        private int STk__BackingFieldField;
        
        private System.DateTime StartDatek__BackingFieldField;
        
        private System.DateTime TimeOfAccidentk__BackingFieldField;
        
        private System.DateTime TimeSleepk__BackingFieldField;
        
        private System.DateTime TimeToiletk__BackingFieldField;
        
        private int ToiletVisitk__BackingFieldField;
        
        private int Versionk__BackingFieldField;
        
        private LeisnerWebApplication.LeisnerRef.Device devk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AccidentID>k__BackingField", IsRequired=true)]
        public int AccidentIDk__BackingField {
            get {
                return this.AccidentIDk__BackingFieldField;
            }
            set {
                if ((this.AccidentIDk__BackingFieldField.Equals(value) != true)) {
                    this.AccidentIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("AccidentIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Amount>k__BackingField", IsRequired=true)]
        public int Amountk__BackingField {
            get {
                return this.Amountk__BackingFieldField;
            }
            set {
                if ((this.Amountk__BackingFieldField.Equals(value) != true)) {
                    this.Amountk__BackingFieldField = value;
                    this.RaisePropertyChanged("Amountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Drinks>k__BackingField", IsRequired=true)]
        public int Drinksk__BackingField {
            get {
                return this.Drinksk__BackingFieldField;
            }
            set {
                if ((this.Drinksk__BackingFieldField.Equals(value) != true)) {
                    this.Drinksk__BackingFieldField = value;
                    this.RaisePropertyChanged("Drinksk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ST>k__BackingField", IsRequired=true)]
        public int STk__BackingField {
            get {
                return this.STk__BackingFieldField;
            }
            set {
                if ((this.STk__BackingFieldField.Equals(value) != true)) {
                    this.STk__BackingFieldField = value;
                    this.RaisePropertyChanged("STk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StartDate>k__BackingField", IsRequired=true)]
        public System.DateTime StartDatek__BackingField {
            get {
                return this.StartDatek__BackingFieldField;
            }
            set {
                if ((this.StartDatek__BackingFieldField.Equals(value) != true)) {
                    this.StartDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("StartDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TimeOfAccident>k__BackingField", IsRequired=true)]
        public System.DateTime TimeOfAccidentk__BackingField {
            get {
                return this.TimeOfAccidentk__BackingFieldField;
            }
            set {
                if ((this.TimeOfAccidentk__BackingFieldField.Equals(value) != true)) {
                    this.TimeOfAccidentk__BackingFieldField = value;
                    this.RaisePropertyChanged("TimeOfAccidentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TimeSleep>k__BackingField", IsRequired=true)]
        public System.DateTime TimeSleepk__BackingField {
            get {
                return this.TimeSleepk__BackingFieldField;
            }
            set {
                if ((this.TimeSleepk__BackingFieldField.Equals(value) != true)) {
                    this.TimeSleepk__BackingFieldField = value;
                    this.RaisePropertyChanged("TimeSleepk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TimeToilet>k__BackingField", IsRequired=true)]
        public System.DateTime TimeToiletk__BackingField {
            get {
                return this.TimeToiletk__BackingFieldField;
            }
            set {
                if ((this.TimeToiletk__BackingFieldField.Equals(value) != true)) {
                    this.TimeToiletk__BackingFieldField = value;
                    this.RaisePropertyChanged("TimeToiletk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ToiletVisit>k__BackingField", IsRequired=true)]
        public int ToiletVisitk__BackingField {
            get {
                return this.ToiletVisitk__BackingFieldField;
            }
            set {
                if ((this.ToiletVisitk__BackingFieldField.Equals(value) != true)) {
                    this.ToiletVisitk__BackingFieldField = value;
                    this.RaisePropertyChanged("ToiletVisitk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Version>k__BackingField", IsRequired=true)]
        public int Versionk__BackingField {
            get {
                return this.Versionk__BackingFieldField;
            }
            set {
                if ((this.Versionk__BackingFieldField.Equals(value) != true)) {
                    this.Versionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Versionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<dev>k__BackingField", IsRequired=true)]
        public LeisnerWebApplication.LeisnerRef.Device devk__BackingField {
            get {
                return this.devk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.devk__BackingFieldField, value) != true)) {
                    this.devk__BackingFieldField = value;
                    this.RaisePropertyChanged("devk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/BWS_ASP")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DeviceNumberk__BackingFieldField;
        
        private LeisnerWebApplication.LeisnerRef.Costumer Ownerk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceNumber>k__BackingField", IsRequired=true)]
        public int DeviceNumberk__BackingField {
            get {
                return this.DeviceNumberk__BackingFieldField;
            }
            set {
                if ((this.DeviceNumberk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Owner>k__BackingField", IsRequired=true)]
        public LeisnerWebApplication.LeisnerRef.Costumer Ownerk__BackingField {
            get {
                return this.Ownerk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Ownerk__BackingFieldField, value) != true)) {
                    this.Ownerk__BackingFieldField = value;
                    this.RaisePropertyChanged("Ownerk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Costumer", Namespace="http://schemas.datacontract.org/2004/07/BWS_ASP")]
    [System.SerializableAttribute()]
    public partial class Costumer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private string Typek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Type>k__BackingField", IsRequired=true)]
        public string Typek__BackingField {
            get {
                return this.Typek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Typek__BackingFieldField, value) != true)) {
                    this.Typek__BackingFieldField = value;
                    this.RaisePropertyChanged("Typek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeisnerRef.IBWSService")]
    public interface IBWSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/ShowGraph", ReplyAction="http://tempuri.org/IBWSService/ShowGraphResponse")]
        void ShowGraph(LeisnerWebApplication.LeisnerRef.Day[] Days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/ShowGraph", ReplyAction="http://tempuri.org/IBWSService/ShowGraphResponse")]
        System.Threading.Tasks.Task ShowGraphAsync(LeisnerWebApplication.LeisnerRef.Day[] Days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/Dowork", ReplyAction="http://tempuri.org/IBWSService/DoworkResponse")]
        void Dowork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/Dowork", ReplyAction="http://tempuri.org/IBWSService/DoworkResponse")]
        System.Threading.Tasks.Task DoworkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/RegisterAccident", ReplyAction="http://tempuri.org/IBWSService/RegisterAccidentResponse")]
        void RegisterAccident(int deviceNR, int amount, System.DateTime timeOfAccident, int Drinks, System.DateTime TimeSleep, System.DateTime TimeToilet, int ToiletVisit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/RegisterAccident", ReplyAction="http://tempuri.org/IBWSService/RegisterAccidentResponse")]
        System.Threading.Tasks.Task RegisterAccidentAsync(int deviceNR, int amount, System.DateTime timeOfAccident, int Drinks, System.DateTime TimeSleep, System.DateTime TimeToilet, int ToiletVisit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetSatisticBasedOnUser", ReplyAction="http://tempuri.org/IBWSService/GetSatisticBasedOnUserResponse")]
        LeisnerWebApplication.LeisnerRef.AccidentDTO[] GetSatisticBasedOnUser(int ID, System.DateTime startdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetSatisticBasedOnUser", ReplyAction="http://tempuri.org/IBWSService/GetSatisticBasedOnUserResponse")]
        System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.AccidentDTO[]> GetSatisticBasedOnUserAsync(int ID, System.DateTime startdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/logIn", ReplyAction="http://tempuri.org/IBWSService/logInResponse")]
        int logIn(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/logIn", ReplyAction="http://tempuri.org/IBWSService/logInResponse")]
        System.Threading.Tasks.Task<int> logInAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/RegisterDevice", ReplyAction="http://tempuri.org/IBWSService/RegisterDeviceResponse")]
        void RegisterDevice(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/RegisterDevice", ReplyAction="http://tempuri.org/IBWSService/RegisterDeviceResponse")]
        System.Threading.Tasks.Task RegisterDeviceAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/UpdateAccident", ReplyAction="http://tempuri.org/IBWSService/UpdateAccidentResponse")]
        void UpdateAccident(int AccidentID, int Amount, System.DateTime date, int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/UpdateAccident", ReplyAction="http://tempuri.org/IBWSService/UpdateAccidentResponse")]
        System.Threading.Tasks.Task UpdateAccidentAsync(int AccidentID, int Amount, System.DateTime date, int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/DeleteAccidents", ReplyAction="http://tempuri.org/IBWSService/DeleteAccidentsResponse")]
        void DeleteAccidents(int AccidentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/DeleteAccidents", ReplyAction="http://tempuri.org/IBWSService/DeleteAccidentsResponse")]
        System.Threading.Tasks.Task DeleteAccidentsAsync(int AccidentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/SignUp", ReplyAction="http://tempuri.org/IBWSService/SignUpResponse")]
        void SignUp(string type, string birthday, string UserName, string PassWord, string Name, int deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/SignUp", ReplyAction="http://tempuri.org/IBWSService/SignUpResponse")]
        System.Threading.Tasks.Task SignUpAsync(string type, string birthday, string UserName, string PassWord, string Name, int deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/ReadAccidents", ReplyAction="http://tempuri.org/IBWSService/ReadAccidentsResponse")]
        LeisnerWebApplication.LeisnerRef.AccidentDTO[] ReadAccidents(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/ReadAccidents", ReplyAction="http://tempuri.org/IBWSService/ReadAccidentsResponse")]
        System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.AccidentDTO[]> ReadAccidentsAsync(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/getIDFromUsername", ReplyAction="http://tempuri.org/IBWSService/getIDFromUsernameResponse")]
        int getIDFromUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/getIDFromUsername", ReplyAction="http://tempuri.org/IBWSService/getIDFromUsernameResponse")]
        System.Threading.Tasks.Task<int> getIDFromUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetDayAccidents", ReplyAction="http://tempuri.org/IBWSService/GetDayAccidentsResponse")]
        LeisnerWebApplication.LeisnerRef.Day[] GetDayAccidents(System.DateTime selectStart, System.DateTime selectEnd, string DeviceNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetDayAccidents", ReplyAction="http://tempuri.org/IBWSService/GetDayAccidentsResponse")]
        System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.Day[]> GetDayAccidentsAsync(System.DateTime selectStart, System.DateTime selectEnd, string DeviceNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetListByDay", ReplyAction="http://tempuri.org/IBWSService/GetListByDayResponse")]
        LeisnerWebApplication.LeisnerRef.Accident[] GetListByDay(System.DateTime Date, string DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWSService/GetListByDay", ReplyAction="http://tempuri.org/IBWSService/GetListByDayResponse")]
        System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.Accident[]> GetListByDayAsync(System.DateTime Date, string DeviceID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBWSServiceChannel : LeisnerWebApplication.LeisnerRef.IBWSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BWSServiceClient : System.ServiceModel.ClientBase<LeisnerWebApplication.LeisnerRef.IBWSService>, LeisnerWebApplication.LeisnerRef.IBWSService {
        
        public BWSServiceClient() {
        }
        
        public BWSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BWSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BWSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BWSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ShowGraph(LeisnerWebApplication.LeisnerRef.Day[] Days) {
            base.Channel.ShowGraph(Days);
        }
        
        public System.Threading.Tasks.Task ShowGraphAsync(LeisnerWebApplication.LeisnerRef.Day[] Days) {
            return base.Channel.ShowGraphAsync(Days);
        }
        
        public void Dowork() {
            base.Channel.Dowork();
        }
        
        public System.Threading.Tasks.Task DoworkAsync() {
            return base.Channel.DoworkAsync();
        }
        
        public void RegisterAccident(int deviceNR, int amount, System.DateTime timeOfAccident, int Drinks, System.DateTime TimeSleep, System.DateTime TimeToilet, int ToiletVisit) {
            base.Channel.RegisterAccident(deviceNR, amount, timeOfAccident, Drinks, TimeSleep, TimeToilet, ToiletVisit);
        }
        
        public System.Threading.Tasks.Task RegisterAccidentAsync(int deviceNR, int amount, System.DateTime timeOfAccident, int Drinks, System.DateTime TimeSleep, System.DateTime TimeToilet, int ToiletVisit) {
            return base.Channel.RegisterAccidentAsync(deviceNR, amount, timeOfAccident, Drinks, TimeSleep, TimeToilet, ToiletVisit);
        }
        
        public LeisnerWebApplication.LeisnerRef.AccidentDTO[] GetSatisticBasedOnUser(int ID, System.DateTime startdate, System.DateTime enddate) {
            return base.Channel.GetSatisticBasedOnUser(ID, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.AccidentDTO[]> GetSatisticBasedOnUserAsync(int ID, System.DateTime startdate, System.DateTime enddate) {
            return base.Channel.GetSatisticBasedOnUserAsync(ID, startdate, enddate);
        }
        
        public int logIn(string username, string password) {
            return base.Channel.logIn(username, password);
        }
        
        public System.Threading.Tasks.Task<int> logInAsync(string username, string password) {
            return base.Channel.logInAsync(username, password);
        }
        
        public void RegisterDevice(int userID) {
            base.Channel.RegisterDevice(userID);
        }
        
        public System.Threading.Tasks.Task RegisterDeviceAsync(int userID) {
            return base.Channel.RegisterDeviceAsync(userID);
        }
        
        public void UpdateAccident(int AccidentID, int Amount, System.DateTime date, int DeviceID) {
            base.Channel.UpdateAccident(AccidentID, Amount, date, DeviceID);
        }
        
        public System.Threading.Tasks.Task UpdateAccidentAsync(int AccidentID, int Amount, System.DateTime date, int DeviceID) {
            return base.Channel.UpdateAccidentAsync(AccidentID, Amount, date, DeviceID);
        }
        
        public void DeleteAccidents(int AccidentID) {
            base.Channel.DeleteAccidents(AccidentID);
        }
        
        public System.Threading.Tasks.Task DeleteAccidentsAsync(int AccidentID) {
            return base.Channel.DeleteAccidentsAsync(AccidentID);
        }
        
        public void SignUp(string type, string birthday, string UserName, string PassWord, string Name, int deviceID) {
            base.Channel.SignUp(type, birthday, UserName, PassWord, Name, deviceID);
        }
        
        public System.Threading.Tasks.Task SignUpAsync(string type, string birthday, string UserName, string PassWord, string Name, int deviceID) {
            return base.Channel.SignUpAsync(type, birthday, UserName, PassWord, Name, deviceID);
        }
        
        public LeisnerWebApplication.LeisnerRef.AccidentDTO[] ReadAccidents(int UserID) {
            return base.Channel.ReadAccidents(UserID);
        }
        
        public System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.AccidentDTO[]> ReadAccidentsAsync(int UserID) {
            return base.Channel.ReadAccidentsAsync(UserID);
        }
        
        public int getIDFromUsername(string username) {
            return base.Channel.getIDFromUsername(username);
        }
        
        public System.Threading.Tasks.Task<int> getIDFromUsernameAsync(string username) {
            return base.Channel.getIDFromUsernameAsync(username);
        }
        
        public LeisnerWebApplication.LeisnerRef.Day[] GetDayAccidents(System.DateTime selectStart, System.DateTime selectEnd, string DeviceNr) {
            return base.Channel.GetDayAccidents(selectStart, selectEnd, DeviceNr);
        }
        
        public System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.Day[]> GetDayAccidentsAsync(System.DateTime selectStart, System.DateTime selectEnd, string DeviceNr) {
            return base.Channel.GetDayAccidentsAsync(selectStart, selectEnd, DeviceNr);
        }
        
        public LeisnerWebApplication.LeisnerRef.Accident[] GetListByDay(System.DateTime Date, string DeviceID) {
            return base.Channel.GetListByDay(Date, DeviceID);
        }
        
        public System.Threading.Tasks.Task<LeisnerWebApplication.LeisnerRef.Accident[]> GetListByDayAsync(System.DateTime Date, string DeviceID) {
            return base.Channel.GetListByDayAsync(Date, DeviceID);
        }
    }
}
